### ISSUE TITLE
modulefixer should convert META-INF/services

### ISSUE THREAD

**Issue by sormuras** [forax/pro#14]
Rémi, the last remaining part of auto-fix is the "provides" support.

See the current exception stacktrace produced by the running "junitconsole" plugin:
```[pro] registered plugins compiler, convention, junitconsole, linker, modulefixer, packager, resolver, runner, uberpackager
org.junit.platform.commons.util.PreconditionViolationException:
  Cannot create Launcher without at least one TestEngine;
  consider adding an engine implementation JAR to the classpath
        at junit.platform.console.standalone@1.0.0_M4/org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:285)
        at junit.platform.console.standalone@1.0.0_M4/org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:52)
        at junit.platform.console.standalone@1.0.0_M4/org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:53)
        at com.github.forax.pro.plugin.junitconsole@0.9/com.github.forax.pro.plugin.junitconsole.JunitConsolePlugin.execute(JunitConsolePlugin.java:36)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.execute(Pro.java:267)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.runAll(Pro.java:247)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.run(Pro.java:237)
        at REPL.$JShell$13.do_it$($JShell$13.java:4)
```

The JAR (and module) contains following lines in `META-INF/services/org.junit.platform.engine.TestEngine`:
```
org.junit.jupiter.engine.JupiterTestEngine
org.junit.vintage.engine.VintageTestEngine
```
...which should be translated to:
**provides** org.junit.platform.engine.TestEngine 
  **with** org.junit.jupiter.engine.JupiterTestEngine;
and
**provides** org.junit.platform.engine.TestEngine 
  **with** org.junit.vintage.engine.VintageTestEngine;

In http://openjdk.java.net/projects/jigsaw/spec/sotms/#services Mark states

_For migration purposes, if a JAR file that defines an automatic module contains META-INF/services resource entries then each such entry is treated as if it were a corresponding provides clause in a hypothetical declaration of that module._

But that is not working, as we're pretending to be a normal module, i.e. not automatic.

**Comment by forax** [comment]
The doc of ServiceLoader [1] is clear that
- either you are in the classpath (or an automatic module in the modulepath) and META-INF/services/ is read
- or you are in the module path and the module-info is read

so yes, i suppose i have to read every entries of META-INF/services to create the corresponding provides directives. 

[1] http://download.java.net/java/jdk9/docs/api/java/util/ServiceLoader.html

**Comment by sormuras** [comment]
```
uses: [org/junit/jupiter/api/extension/Extension, org/junit/platform/engine/TestEngine, org/junit/platform/launcher/TestExecutionListener]
provides: {}
[modulefixer] fix junit.platform.console.standalone
```

The current implemetation does not fill the "provides" mapping correctly. It's empty. Didn't find the reason, yet.
