### ISSUE TITLE
Build pro with pro

### ISSUE THREAD

**Issue by sormuras** [forax/pro#20]
## `build.pro` skeleton
```
import static com.github.forax.pro.Pro.*;

set("pro.loglevel", "verbose")

// rm -fr bootstrap
// mkdir bootstrap

// TODO 1: remove & create bootstrap directory

// $javac --module-source-path src/main/java \
//           -d bootstrap/modules/ \
//           --module-path deps \
//           $(find src/main/java/ -name "*.java")

// TODO 2: configure compiler(?) module like "javac" above

set("packager.moduleMetadata", list(
  "com.github.forax.pro.bootstrap/com.github.forax.pro.bootstrap.Bootstrap"
))

// $java --module-path bootstrap/modules:deps \
//       --module com.github.forax.pro.bootstrap/com.github.forax.pro.bootstrap.Bootstrap

set("runner.modulePath", list("bootstrap/modules", "deps"))

run("compiler", "packager", "runner")

```

_"TODO 2"_ is related to #19

**Comment by sormuras** [comment]
Almost works: https://travis-ci.org/sormuras/pro/builds/222839573

The *uberpackager* is throwing an exception:
```
java.nio.file.ProviderMismatchException
	at java.base/sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:198)
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:410)
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:43)
	at com.github.forax.pro.plugin.uberpackager@0.9/com.github.forax.pro.plugin.uberpackager.UberPackagerPlugin.execute(UberPackagerPlugin.java:85)
	at com.github.forax.pro@0.9/com.github.forax.pro.Pro.execute(Pro.java:267)
	at com.github.forax.pro@0.9/com.github.forax.pro.Pro.runAll(Pro.java:247)
	at com.github.forax.pro@0.9/com.github.forax.pro.Pro.run(Pro.java:237)
	at REPL.$JShell$22.do_it$($JShell$22.java:4)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:563)
	at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:198)
	at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:107)
	at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:108)
	at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:134)
	at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:225)
	at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76)
	at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137)
	at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70)
[uberpackager] null
|  State engine terminated.
|  Restore definitions with: /reload -restore
```

**Comment by sormuras** [comment]
Playing with pro building pro here: https://github.com/forax/pro/compare/master...sormuras:pro_builds_pro
