### ISSUE TITLE
Extend list of repository roots

### ISSUE THREAD

**Issue by sormuras** [forax/pro#6]
Class `Aether` in `com.github.forax.pro.aether` registers Maven Central as single root, like around line 65:
```
RemoteRepository mavenCentral = new RemoteRepository.Builder("central", "default",
    "http://central.maven.org/maven2/").build();
```

Is there already a programmatic way to extend that list with other root urls? I need to fetch some snapshots artifacts from https://oss.sonatype.org/content/repositories/snapshots/org/junit 😉

**Comment by forax** [comment]
Ok, i've just pushed a fix, let's try this:
  set("compiler.remoteRepositories", list(
    uri("https://oss.sonatype.org/content/repositories/snapshots/org/junit")
  ))

I'm not sure it works, the doc on aether is really light.

**Comment by sormuras** [comment]
**IAE** -- the new NPE.

```
[pro] registered plugins compiler, convention, linker, modulefixer, packager, resolver, runner, uberpackager
|  java.lang.IllegalAccessError thrown: class org.apache.maven.repository.internal.DefaultVersionResolver (in module maven.aether.provider) cannot access class org.codehaus.plexus.util.IOUtil (in module plexus.utils) because module maven.aether.provider does no
t read module plexus.utils
|        at DefaultVersionResolver.readVersions (DefaultVersionResolver.java:377)
|        at DefaultVersionResolver.resolveVersion (DefaultVersionResolver.java:251)
|        at DefaultArtifactDescriptorReader.loadPom (DefaultArtifactDescriptorReader.java:231)
|        at DefaultArtifactDescriptorReader.readArtifactDescriptor (DefaultArtifactDescriptorReader.java:198)
|        at DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:202)
|        at DefaultRepositorySystem.collectDependencies (DefaultRepositorySystem.java:316)
|        at Aether.dependencies (Aether.java:94)
|        at ResolverPlugin.execute (ResolverPlugin.java:144)
|        at Pro.execute (Pro.java:267)
|        at Pro.runAll (Pro.java:247)
|        at Pro.run (Pro.java:237)
|        at (#5:1)

```

**Comment by forax** [comment]
Ok, yet again a dependencies not found with the static analysis,
should be fixed now (famous last world)

**Comment by sormuras** [comment]
Almost there:
```
[pro] registered plugins compiler, convention, linker, modulefixer, packager, resolver, runner, uberpackager
download unresolvedArtifacts [com.github.forax.pro.aether.ArtifactInfo@b7133998, com.github.forax.pro.aether.ArtifactInfo@6655d230, com.github.forax.pro.aether.ArtifactInfo@71d1b4e]
java.io.IOException: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT, org.junit.platform:junit-platform-commons:jar:1.0.0-SNAPSHOT, org.opentest4j:o
pentest4j:jar:1.0.0-SNAPSHOT: Could not find artifact org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT in central (http://central.maven.org/maven2/)
        at com.github.forax.pro.aether@0.9/com.github.forax.pro.aether.Aether.download(Aether.java:137)
        at com.github.forax.pro.plugin.resolver@0.9/com.github.forax.pro.plugin.resolver.ResolverPlugin.execute(ResolverPlugin.java:153)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.execute(Pro.java:267)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.runAll(Pro.java:247)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.run(Pro.java:237)
        at REPL.$JShell$15.do_it$($JShell$15.java:4)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:547)
        at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:198)
        at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:107)
        at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:108)
        at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:134)
        at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:225)
        at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76)
        at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137)
        at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT, org.junit.platform:junit-platform-commons:jar:1.0.0-SNAPSHOT, org.opentest4j:opentest4j:
jar:1.0.0-SNAPSHOT: Could not find artifact org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT in central (http://central.maven.org/maven2/)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifacts(DefaultRepositorySystem.java:302)
        at com.github.forax.pro.aether@0.9/com.github.forax.pro.aether.Aether.download(Aether.java:135)
        ... 17 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT in central (http://central.maven.org/maven2/)
        at aether.connector.basic@1.0.1/org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
        at aether.connector.basic@1.0.1/org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at aether.util@1.0.1/org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1161)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
[resolver] org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT, org.junit.platform:junit-platform-commons:jar:1.0.0-SNAPSHOT, org.opentest4j:opentest4j:
jar:1.0.0-SNAPSHOT: Could not find artifact org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT in central (http://central.maven.org/maven2/)
[pro] FAILED !        elapsed time 1.110 ms
```

**Comment by sormuras** [comment]
Ah! There was a typo in

> Ok, i've just pushed a fix, let's try this:
> set("compiler.remoteRepositories", list(
> uri("https://oss.sonatype.org/content/repositories/snapshots/org/junit")
> ))

After changing it to `set("resolver.remote...` I get another error:
```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.junit.jupiter:junit-jupiter-api:pom:5.0.0-SNAPSHOT from/to  (https://oss.sonatype.org/content/repositories/snapshots/org/junit): Cannot access https://oss.sonatype
.org/content/repositories/snapshots/org/junit with type  using the available connector factories: BasicRepositoryConnectorFactory
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:531)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 24 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access https://oss.sonatype.org/content/repositories/snapshots/org/junit with type  using the available connector factories: BasicRepositoryConnectorFactory
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:174)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
        ... 25 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access https://oss.sonatype.org/content/repositories/snapshots/org/junit with type  using the available layout factories: Maven2RepositoryLayoutFactory
        at aether.connector.basic@1.0.1/org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:111)
        at aether.connector.basic@1.0.1/org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
        ... 26 more
Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Cannot access https://oss.sonatype.org/content/repositories/snapshots/org/junit with type  using the available layout factories: Maven2RepositoryLayoutFactory
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:142)
        at aether.connector.basic@1.0.1/org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:107)
        ... 28 more
Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Unsupported repository layout
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory.newInstance(Maven2RepositoryLayoutFactory.java:64)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:111)
        ... 29 more

```

**Comment by sormuras** [comment]
When using the root *cough* with
```
set("resolver.remoteRepositories", list(
    uri("https://oss.sonatype.org/content/repositories/snapshots")
))
```
I still get:
```
[pro] registered plugins compiler, convention, linker, modulefixer, packager, resolver, runner, uberpackager
java.io.IOException: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT
        at com.github.forax.pro.aether@0.9/com.github.forax.pro.aether.Aether.dependencies(Aether.java:96)
        at com.github.forax.pro.plugin.resolver@0.9/com.github.forax.pro.plugin.resolver.ResolverPlugin.execute(ResolverPlugin.java:144)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.execute(Pro.java:267)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.runAll(Pro.java:247)
        at com.github.forax.pro@0.9/com.github.forax.pro.Pro.run(Pro.java:237)
        at REPL.$JShell$15.do_it$($JShell$15.java:4)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:547)
        at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:198)
        at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.invoke(RemoteExecutionControl.java:107)
        at jdk.jshell/jdk.jshell.execution.DirectExecutionControl.invoke(DirectExecutionControl.java:108)
        at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.processCommand(ExecutionControlForwarder.java:134)
        at jdk.jshell/jdk.jshell.execution.ExecutionControlForwarder.commandLoop(ExecutionControlForwarder.java:225)
        at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControl(Util.java:76)
        at jdk.jshell/jdk.jshell.execution.Util.forwardExecutionControlAndIO(Util.java:137)
        at jdk.jshell/jdk.jshell.execution.RemoteExecutionControl.main(RemoteExecutionControl.java:70)
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:208)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
        at com.github.forax.pro.aether@0.9/com.github.forax.pro.aether.Aether.dependencies(Aether.java:94)
        ... 17 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT
        at maven.aether.provider@3.3.9/org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
        at maven.aether.provider@3.3.9/org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:202)
        ... 19 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.junit.jupiter:junit-jupiter-api:pom:5.0.0-SNAPSHOT from/to  (https://oss.sonatype.org/content/repositories/snapshots): Cannot access https://oss.sonatype.org/c
ontent/repositories/snapshots with type  using the available connector factories: BasicRepositoryConnectorFactory
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at maven.aether.provider@3.3.9/org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
        ... 21 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.junit.jupiter:junit-jupiter-api:pom:5.0.0-SNAPSHOT from/to  (https://oss.sonatype.org/content/repositories/snapshots): Cannot access https://oss.sonatype.org/conte
nt/repositories/snapshots with type  using the available connector factories: BasicRepositoryConnectorFactory
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:531)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 24 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access https://oss.sonatype.org/content/repositories/snapshots with type  using the available connector factories: BasicRepositoryConnectorFactory
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:174)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
        ... 25 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access https://oss.sonatype.org/content/repositories/snapshots with type  using the available layout factories: Maven2RepositoryLayoutFactory
        at aether.connector.basic@1.0.1/org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:111)
        at aether.connector.basic@1.0.1/org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
        ... 26 more
Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Cannot access https://oss.sonatype.org/content/repositories/snapshots with type  using the available layout factories: Maven2RepositoryLayoutFactory
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:142)
        at aether.connector.basic@1.0.1/org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:107)
        ... 28 more
Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Unsupported repository layout
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory.newInstance(Maven2RepositoryLayoutFactory.java:64)
        at aether.impl@1.0.1/org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:111)
        ... 29 more
[resolver] org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for org.junit.jupiter:junit-jupiter-api:jar:5.0.0-SNAPSHOT
[pro] FAILED !        elapsed time 705 ms
```

**Comment by forax** [comment]
Ok, my bad,
it seems i've to specify a layout ("default") for the remote repositories
(the last change should fix that).

**Comment by sormuras** [comment]
Great. I call it a day (night), Rémi. Tomorrow, there be pro-plugins: JUnit-5 runner and google-java-format

```
[pro] registered plugins compiler, convention, linker, modulefixer, packager, resolver, runner, uberpackager
download unresolvedArtifacts [com.github.forax.pro.aether.ArtifactInfo@b7133998, com.github.forax.pro.aether.ArtifactInfo@71d1b4e, com.github.forax.pro.aether.ArtifactInfo@6655d230]
[resolver] resolved artifacts [org.junit.jupiter:junit-jupiter-api:jar:5.0.0-20170327.190034-479, org.opentest4j:opentest4j:jar:1.0.0-20170311.222705-42, org.junit.platform:junit-platform-commons:jar:1.0.0-20170327.190053-478]
[resolver] org.junit.jupiter.api (org.junit.jupiter:junit-jupiter-api:jar:5.0.0-20170327.190034-479) downloaded from repositories
[resolver] org.opentest4j (org.opentest4j:opentest4j:jar:1.0.0-20170311.222705-42) downloaded from repositories
[resolver] org.junit.platform.commons (org.junit.platform:junit-platform-commons:jar:1.0.0-20170327.190053-478) downloaded from repositories
[modulefixer] fix org.junit.jupiter.api
[modulefixer] fix org.opentest4j
[modulefixer] fix org.junit.platform.commons
[pro] DONE !          elapsed time 10.574 ms
```
